### ISSUE TITLE
ALNS Operators

### ISSUE THREAD

**Issue by bengisu-sahin** [bengisu-sahin/ALNS-Implemantation-On-EVRP#9]
1. alnsOperators diye yeni bir branch açıldı.
2. randomStationRemoval, worstChargeUsageStationRemoval, removeRandomCustomer, relatedCustomerRemoval ve leastTimeWindowRemoval yazıldı ancak test işlemleri yapılıp buglar fixlenecek.
3. Route sınıfına yeni metotlar eklendi operatör işlemleri için.
4. Şarj istasyonlarındaki herbir operator için ayrı bir sınıf tanımlanmıştı. Bu müşterilerde yapıldığı gibi tek sınıf altında operator metotları olarak düzeltilecek.
5. eneryModel sınıfı kullanılmamıştır deneme yapılmıştır.

Yeni güncellemeler bu şekilde. Her şekilde operatörlerin manuel olarak yazılması gerekeceği için (alns için kütüphane kullanılsa bile) buradan başladım. Test işlemlerini akşam veya yarın yapacağım. Operatörler için sınıf tanımladım ağırlıklar vs tutuluyor. Ancak dediğim gibi test ve bug fix daha tamamlanmadı ancak branch de durması için attım. 

Rulet seçiminde ise ağırlık matrisi oluşturulması gerektekmeymiş anladığım kadarıyla operatörlerin uyumlu çalışması için bunu rulet sınıfı oluşturur öyle tanımlarız diye operator sınıfına veya rota sınıfına vs eklemedim.

Enerji modeli dosyası da şu anda makaledeki formülü uyguluyor. Xml dosyasından okuma yapmıyor ancak oradaki alınan verileri denedim sadece.

Q ve P kadar müşteri veya şarj istasyonu çıkarılması yapılacak. P kadar müşteri çıkacak bir rotadan diye düşündüm bu arada.

Güncellemeler bu şekilde....kod daha tam değil  dediğim gibi ancak yorum satırı da yazmaya çalıştım anlaşılır olması bakılması için

@yagizharman

**Comment by yagizharman** [comment]
Operatorlerin içerisinde hizmet edilen ve edilmeyen müşterilerin tutulması gerekecek. Instancelardan birinin içinde tanımlanabilir

Operator sınıfının içerisinde neden rota var? customer ve station operatorleri için bence örneğin pseudocodedaki gibi callCustomerRemoval(routes) dediğimizde mesela :
Önce bir customer removal operatorü seçip sonra onu çağırıp
müşterilerin rotadan çıktığı bir çözümğ döndürmesi lazım.

Enerji modelini bende denedim bir yerde hata var ama tam emin değilim onun acelesi yok yapılabilir.

Kodu yazmadan önce genel tasarım fikrini konuşup kararlaştırsaydık daha net yazılabilirdi.

Müsait olduğunda genel kod yapısı hakkında bir toplantı yapalım. Çarşamba günü için müsaitsen akşam için eğer görüşebiliriz.

Eline sağlık.
